name: Upload Asset

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Wrapping up
        run: zip -r release.zip build
      - name: Release
        uses: phuonghuynh/action-ghrelease@v1.1.0
        with:
          files: release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
